### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by xiaowodaweiwang** [vyrjana/pyimpspec#7]
Dear vyrjana,
I'm trying to accelerated processing the circuit fit when treat batch process, I adopted multiprocess by using 6 num_workers to process a dataset with 20 frequencies and the batch size is 20，the time cost of common loop is 69.77 seconds, and the multiprocess is 22.28 seconds， but it is too long for me?
Do you have some tips for multiprocess for speeding up ? 
Thanks a lot!

**Comment by vyrjana** [comment]
I don't think I quite understand how you've structured your code. Are you using the [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) module in your code or are you adjusting the `num_procs` parameter when calling [`pyimpspec.fit_circuit`](https://vyrjana.github.io/pyimpspec/apidocs_fitting.html#pyimpspec.fit_circuit)? Could you provide an example?

Are you choosing a specific a fitting method and a specific weight when calling `pyimpspec.fit_circuit`? If you have left one or both of those settings at the default `"auto"`, then picking values for those parameters would be one way of reducing the amount of time that is required. However, if you do that, then you might not get the best fit possible or you might have to be more careful about choosing the initial values for your circuit(s).

**Comment by xiaowodaweiwang** [comment]
Dear vyrjana, here is my code for multiprocessing, Actually I use the default "auto" for pyimpspec.fit_circuit.
```
import multiprocessing
import time

def single(num):
    data = parse_data(os.path.join(data_path, 'test_data.xlsx'))[0]
    circuit = parse_cdc("R(RC)(RC)")
    result = fit_circuit(circuit, data)
    return result

if __name__ == '__main__':
    numbers = list(np.arange(20))

    start_time = time.time()
    results = []
    for num in numbers:
        results.append(single(num))
    end_time = time.time()
    print("time of common loops:", end_time - start_time)

    start_time = time.time()
    pool = multiprocessing.Pool(processes=6)
    results = pool.map(single, numbers)
    pool.close()
    pool.join()
    end_time = time.time()
    print("time of multiprocess: ", end_time - start_time)
```

And result of the code is 72.81959891319275s and 21.667062520980835s

**Comment by vyrjana** [comment]
I set up a slightly modified version of your script (still using 20 repetitions) and was able to get the average total time for the for-loop down from around 60 s to 1 s (tested on an AMD Ryzen 5 3600 with 32 GB of 3200 MT/s CL16 DDR4 RAM). I did this by calling `fit_circuit` with `method="least_squares"` and `method="modulus"`, which means that pyimpspec only has one combination to process. I had to try a few different methods and weights to find a combination that worked well for the impedance spectrum that I was fitting the circuits to. If I also use `multiprocessing.Pool.map` with six processes instead of the for-loop, then the average total time drops down to about 0.5 s.

If I kept `method="auto"` and `method="auto"` but set `num_procs=6` when calling `fit_circuit`, then I got the average total time for the for-loop down from 60 s to 14 s. Setting `num_procs=6` [makes pyimpspec use `multiprocessing.Pool.imap_unordered` instead of a for-loop to process all of the combinations of methods and weights](https://github.com/vyrjana/pyimpspec/blob/6b87a656190c14e55c11e4a79933a4f45d8a25b2/src/pyimpspec/analysis/fitting.py#L845-L849).

What are you trying to accomplish with the batch fitting? If you are simply fitting the same circuit to multiple nearly-identical impedance spectra (e.g., for quality assurance testing), then there are two general approaches that you can choose from:

- Spend more time doing the fitting so that the various combinations of methods and weights can be processed (i.e., keep using `method="auto"` and `weight="auto"`). This is slow but most likely to produce good fits without requiring you to carefully choose, e.g., the initial values for your circuit(s).

- Optimize your settings in order to speed up the fitting process:
  - Which method and weight combination works well? One of those two settings could even be set to `"auto"`, but as long as you choose a value for the other, the number of combinations is reduced and the total time needed for fitting is also reduced.
  - If you are always testing the same circuit, then you can probably pick decent initial values for the parameters of your circuit so that the fitting method can converge on a solution faster. For example, the default initial value for a resistance is 1000 ohms in pyimpspec, but that might be far from the values you would expect (e.g., maybe only a few ohms). Also, if you have repeating units like `(RC)(RC)`, then the fitting method might struggle a bit if the initial values of the parameters are identical.
  - Likewise, you can probably set stricter lower and/or upper limits for the parameters of your circuit. This would help to reduce the solution space and could speed up the fitting as well (depending on the limits and the fitting method).
  - You can also limit the number of function evaluations (e.g., `max_nfev=50`). However, the fitting method might not manage to converge on a solution if this limit is too low, which can lead to very poor fits.

**Comment by xiaowodaweiwang** [comment]
Dear vyrjana:
 I change the code like this:
```
 fits = []
    for res in pool.imap_unordered(single, numbers):
        fits.append(res)
```
and the time cost is 20.91s for 20 loops. By the way, I repeat 20 cycles for same dataframe just only for  simulating when process 20 different dataframes.
 
Also，just replace `auto` with `method="least_squares" and weight="modulus"` could indeed greatly reduce time. here is 0.8s.
I think `auto` is more stable because multiple methods will be tested in parallel and the best result was choosen, 
Moreover the initial value is very important when does the nonlinear fit. Do you have some tips about how to choose a "better" initial value for different siutations?
Thanks!

**Comment by vyrjana** [comment]
Ideally, the initial values would of course be fairly close to the final fitted values. If you are fitting a single circuit to many different spectra, then I would assume that the spectra are somewhat similar. In that case, you could try to manually figure out suitable initial values for one of the spectra and then use those initial values for the batch fitting of the remaining spectra. You can try to fit the circuit to one spectrum and then use the fitted values as the initial values. Alternatively, you can manually try to figure out rough approximations (e.g., estimate the series resistance using the real part of the impedance at the high-frequency end of the spectrum).
